routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm']);

Route::middleware(['middleware'=>'back'])->group(function (){
    Auth::routes([
//        'register'=>false
    ]);

});

Route::group(['prefix'=>'dashboard', 'middleware'=>['auth', 'admin', 'back']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'adminpanel'])->name('adminpanel');
    Route::resource('/direction', \App\Http\Controllers\Admin\YonalishController::class);
    Route::resource('/course', \App\Http\Controllers\Admin\CourseController::class);
    Route::resource('/group', \App\Http\Controllers\Admin\GroupController::class);
    Route::resource('/student', \App\Http\Controllers\Admin\StudentController::class);
    Route::get('/active/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'active'])->name('student.active');
    Route::get('/active/group/student/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'activeGroupStudent'])->name('activeGroupStudent');
    Route::get('/noactive/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'noactive'])->name('student.noactive');
    Route::get('/noactive/group/student/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'noactiveGroupStudent'])->name('noactiveGroupStudent');
    Route::get('/certificate/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'certi'])->name('student.certi');
    Route::get('/plastik/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'plastik'])->name('student.plastik');
    Route::get('/enable/{group}', [\App\Http\Controllers\Admin\GroupController::class, 'active'])->name('group.active');
    Route::get('/enable_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'active_org'])->name('group.active_org');
    Route::get('/disable_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'noactive_org'])->name('group.noactive_org');
    Route::get('/disable/{group}', [\App\Http\Controllers\Admin\GroupController::class, 'noactive'])->name('group.noactive');
    Route::get('/course/groups/{course}', [\App\Http\Controllers\Admin\CourseController::class, 'course_item'])->name('course.itemGroup');
    Route::get('/course/groups/create/{course}', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupCourse'])->name('createGroupCourse');
    Route::post('/course/groups/create/store', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupStore'])->name('createGroupCourseStore');
    Route::get('/course/groups/create/student/{group}', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupCourseStudent'])->name('createGroupCourseStudent');
    Route::post('/course/groups/student/store', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupCourseStudentStore'])->name('createGroupCourseStudentStore');

    Route::get('/group/students/{group}', [\App\Http\Controllers\Admin\GroupController::class, 'group_item'])->name('group.itemStudent');
    Route::get('/group/students/edit/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'editGroupStudent'])->name('editGroupStudent');
    Route::put('/group/students/edit/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'updateGroupStudent'])->name('updateGroupStudent');
    Route::resource('/guvohnoma', \App\Http\Controllers\Admin\GuvohnomaController::class);
    Route::get('/edit_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'edit_org'])->name('group.edit_org');
    Route::put('/group_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'update_org'])->name('group.update_org');
});

Route::get('/users/{student}',[\App\Http\Controllers\Admin\StudentController::class, 'show'])->name('show.info');

resources/views/admin/certificate/create.blade.php
@extends('admin.layouts.master')
@section('title', 'Гувохнома яратиш')
@section('content')
    <div class="card">
        <div class="card-body">
            <form class="" action="{{route('guvohnoma.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('POST')
                <div class="mb-3">
                    <label for="tur_title">Гувохнома номи</label>
                    <input name="tur_title" class="form-control @error('tur_title') is-invalid @enderror"
                           type="text" placeholder="Гувохнома номи">
                    @error('tur_title')
                    <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Гувохнома яратиш</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/certificate/edit.blade.php
@extends('admin.layouts.master')
@section('title', 'Гувохнома таҳрирлаш')
@section('content')
    <div class="card">
        <div class="card-body">
            <form class="" action="{{route('guvohnoma.update', $guvohnoma)}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="mb-3">
                    <label for="tur_title">Гувохнома номи</label>
                    <input value="{{$guvohnoma->tur_title}}" name="tur_title" class="form-control @error('tur_title') is-invalid @enderror"
                           type="text" placeholder="Гувохнома номи">
                    @error('tur_title')
                    <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Гувохнома яратиш</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/certificate/index.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Document</title>
</head>
<body>
<textarea id="cer">

<main class='main'>
<div class='row'>
<p class='title' > <b style='font-size: 1.2em;'>УДОСТОВЕРЕНИЕ </b> <b class='ml'  style='color: red; font-size: 1.2em;'> №{{$student->id}}</b></p>
<div class='row-2' style='font-size: 1rem;' >
<div class='img'>
  <img width='120' height='150' src='{{asset('images/students/'.$student->student_img)}}'/>
</div>
<p class='font'> Выдано: <b class='font1'>  {{$student->student_fio}} </b>
<br> в том, что он (а) с  {{$student->group_name->start_date}}  года по  {{$student->group_name->end_date}}  года обучался (лось) по профессии</p>
</div>
<p class='font'  ><b class='font1'>{{$student->group_name->kurslar->course_title}} </b>  </p>
<p class='center ' style='margin: 0px'> <span style='font-size:12px ;'> (наименование профессии) </span> </p>
<p class='font' >  {{$student->group_name->kurslar->showStudyPlan->plan_title}} </p>
<p class='center' style='margin: 0px'> <span style='font-size:12px;'> (форма обучения)</span> </p>
<p class='font' > <b class='font1'> НОУ«Саноат техника универсал Сервис» </b> г.Бухара </p>
<p class='center' style='margin: 0px'> <span style='font-size:12px;'> (наименование предприятия организации) </span> </p>
<p class='last'>Прошел(а) полный курс теоретического обучения в объеме {{$student->group_name->kurslar->nazariy_soat}} часов и производственного обучения в объеме  {{$student->group_name->kurslar->amaliy_soat}} часов и сдал(а) квалификационный экзамен с оценками:<p>
<p><b style='font-size: 1.2em;'>- теория:  {{$student->nazariy_baho}} </b> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b style='font-size: 1.2em;'>- практика: {{$student->amaliy_baho}}  </b>   </p>
<p>  </p>

</div>
<div class='row' style='margin-left:26px'>
<p class='font'  > Решением (Экзаменационной)<br> Квалификационной комиссии</p>
<p  class='font' > от 15-09-2022</b>  г  Протокол №{{$student->id}}  </p>
<p  class='center title-2' > <b class='font1'>гр  {{$student->student_fio}}</b> </p> <br>
<p class='last'> Установлен тарифно-квалификационный <br> разряд (класс категория) 5 (V) пятого разряда   <br>  по профессии:</p>
<p class='font1' ><b class='font'>{{$student->group_name->kurslar->course_title}}</b>  </p> <br>
<p class='last1' >Председатель  квалификационной комиссии:______________________________  </p>
<br>
<p class='last' >Руководитель  предприятия <br> Организации:__________________________  <br>           </p>
<br> <br><br>
<p class='last' > <b style='font-size: 0.9em;'>М.П.<br> НОУ«Саноат  техника  универсал <br> сервис»    <b> </p>
{{--<div  class='top' style='max-width: 30mm;max-height: 30mm; border: 0px;'> <iframe style='max-width: 30mm;max-height: 30mm; border: 0px;' src='{{asset('images/qrcodes/'.$student->qr_name)}}'    title='Iframe Example'></iframe></div>--}}
<div class='top'>
  <img width='120' height='150' src='{{asset('images/qrcodes/'.$student->qr_name)}}'/>
</div>
    </div>
</main>




</textarea>
<script src="https://cdn.tiny.cloud/1/r7ku41z0cm85xqcatrbgnudof55uzawklyryk9v5w31n6j2n/tinymce/5/tinymce.min.js"
        referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: '#cer',
        height: 800,
        plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table contextmenu paste pagebreak"
        ],
        toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image pagebreak',
        toolbar_mode: 'floating',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Author name',
        pagebreak_split_block: true,
        content_css: ["{{ asset('styles/assets/css/cer.css') }}"]
    });
</script>

</body>
</html>

resources/views/admin/certificate/view.blade.php
@extends('admin.layouts.master')
@section('title', 'Гувохномалар рўйхати')
@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>СТ Универсалда гувохномалар рўйхати</h5>
                        <span>Ushbu jadvaldan siz ta'lim muassasidagi o'quv rejalarini ko'rishingiz, tahrirlash ishlarini, shuningdek o'quv rejani bazadan o'chirib tashlashingiz mumkin.</span>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive product-table">
                            <table class="display" id="basic-1">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th class="col-sm-3">Гувохномалар номи</th>
                                    <th class="col-sm-3">Гувохномалар яратилган вакти</th>
                                    <th>Тахрирлаш</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($guvohnomas as $guvohnoma)
                                    <tr>
                                        <td>{{$loop->index+1}}</td>
                                        <td class="col-sm-3">
                                            {{$guvohnoma->tur_title}}
                                        </td>
                                        <td class="col-sm-3">
                                            {{ date('d-m-Y', strtotime($guvohnoma->created_at))}}
                                        </td>
                                        <td>
                                            <a class="btn btn-primary" href="{{route('guvohnoma.edit', $guvohnoma)}}" style="padding: 6px 10px ;"><i class="far fa-edit"></i></a>
                                            <form class="d-inline-block" method="post" action="{{route('guvohnoma.destroy', $guvohnoma)}}">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger show_confirm" data-toggle="tooltip" title='Delete' style="padding: 6px 10px ;"><i class="far fa-trash-alt"></i></button>
                                            </form>

                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@push('script')
    <script type="text/javascript">

        $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Ушбу гувохномани ўчирмоқчимисиз?`,
                // text: "If you delete this, it will be gone forever.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });

    </script>
@endpush