routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm']);

Route::middleware(['middleware'=>'back'])->group(function (){
    Auth::routes([
//        'register'=>false
    ]);

});

Route::group(['prefix'=>'dashboard', 'middleware'=>['auth', 'admin', 'back']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'adminpanel'])->name('adminpanel');
    Route::resource('/direction', \App\Http\Controllers\Admin\YonalishController::class);
    Route::resource('/course', \App\Http\Controllers\Admin\CourseController::class);
    Route::resource('/group', \App\Http\Controllers\Admin\GroupController::class);
    Route::resource('/student', \App\Http\Controllers\Admin\StudentController::class);
    Route::get('/active/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'active'])->name('student.active');
    Route::get('/active/group/student/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'activeGroupStudent'])->name('activeGroupStudent');
    Route::get('/noactive/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'noactive'])->name('student.noactive');
    Route::get('/noactive/group/student/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'noactiveGroupStudent'])->name('noactiveGroupStudent');
    Route::get('/certificate/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'certi'])->name('student.certi');
    Route::get('/plastik/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'plastik'])->name('student.plastik');
    Route::get('/enable/{group}', [\App\Http\Controllers\Admin\GroupController::class, 'active'])->name('group.active');
    Route::get('/enable_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'active_org'])->name('group.active_org');
    Route::get('/disable_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'noactive_org'])->name('group.noactive_org');
    Route::get('/disable/{group}', [\App\Http\Controllers\Admin\GroupController::class, 'noactive'])->name('group.noactive');
    Route::get('/course/groups/{course}', [\App\Http\Controllers\Admin\CourseController::class, 'course_item'])->name('course.itemGroup');
    Route::get('/course/groups/create/{course}', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupCourse'])->name('createGroupCourse');
    Route::post('/course/groups/create/store', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupStore'])->name('createGroupCourseStore');
    Route::get('/course/groups/create/student/{group}', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupCourseStudent'])->name('createGroupCourseStudent');
    Route::post('/course/groups/student/store', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupCourseStudentStore'])->name('createGroupCourseStudentStore');

    Route::get('/group/students/{group}', [\App\Http\Controllers\Admin\GroupController::class, 'group_item'])->name('group.itemStudent');
    Route::get('/group/students/edit/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'editGroupStudent'])->name('editGroupStudent');
    Route::put('/group/students/edit/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'updateGroupStudent'])->name('updateGroupStudent');
    Route::resource('/guvohnoma', \App\Http\Controllers\Admin\GuvohnomaController::class);
    Route::get('/edit_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'edit_org'])->name('group.edit_org');
    Route::put('/group_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'update_org'])->name('group.update_org');
});

Route::get('/users/{student}',[\App\Http\Controllers\Admin\StudentController::class, 'show'])->name('show.info');

app/Http/Controllers/Admin/GroupController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Domain\Admin\Courses\Models\Course;
use App\Domain\Admin\Groups\Actions\StoreGroupAction;
use App\Domain\Admin\Groups\Actions\UpdateGroupAction;
use App\Domain\Admin\Groups\DTO\StoreGroupDTO;
use App\Domain\Admin\Groups\DTO\UpdateGroupDTO;
use App\Domain\Admin\Groups\Models\Group;
use App\Domain\Admin\Groups\Repositories\GroupRepository;
use App\Domain\Admin\Groups\Requests\StoreGroupRequest;
use App\Domain\Admin\Groups\Requests\UpdateGroupRequest;
use App\Domain\Admin\Students\Actions\StoreStudentAction;
use App\Domain\Admin\Students\DTO\StoreStudentDTO;
use App\Domain\Admin\Students\Models\Student;
use App\Domain\Admin\Students\Requests\StoreStudentRequest;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use RealRashid\SweetAlert\Facades\Alert;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index(GroupRepository $repository)
    {
        $groups = $repository->getAll();
        return view('admin.groups.index', compact('groups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        $courses = Course::all();
        return view('admin.groups.create', compact('courses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Http\Response|\Illuminate\Routing\Redirector
     */
    public function store(StoreGroupRequest $request, StoreGroupAction $action)
    {
        try {
            $dto = StoreGroupDTO::fromArray($request->all());
            $action->execute($dto);
        }catch (\Exception $exception)
        {
            return redirect()->back();
        }
        Alert::success('Success Title', 'Гуруҳ мувофаққиятли яратилди');
        return redirect()->route('group.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * @param Group $group
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|void
     */
    public function edit(Group $group)
    {
        $courses = Course::all();
        $start_date = date("Y-m-d", strtotime($group->start_date));
        $end_date = date("Y-m-d", strtotime($group->end_date));
        return view('admin.groups.edit', compact('group', 'courses','start_date','end_date'));
    }

    public function edit_org($course_id, $group_id)
    {
        $courses = Course::all();
        $course = DB::table('courses')
            ->where('id','=', $course_id)->first();
        $group = Group::where('id','=',$group_id)->first();
        $start_date = date("Y-m-d", strtotime($group->start_date));
        $end_date = date("Y-m-d", strtotime($group->end_date));
        return view('admin.groups.edit_org', compact('group', 'courses', 'course', 'start_date','end_date'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Http\Response|\Illuminate\Routing\Redirector
     */
    public function update(UpdateGroupRequest $request, Group $group, UpdateGroupAction $action)
    {
        try {
            $request->merge([
                'group'=>$group
            ]);
            $dto = UpdateGroupDTO::fromArray($request->all());
            $action->execute($dto);
        }catch (\Exception $exception)
        {
            return redirect()->back();
        }
        Alert::success('Success Title', 'Гуруҳ мувофаққиятли ўзгартирилди');
        return redirect()->route('group.index');
    }

    /**
     * @param UpdateGroupRequest $request
     * @param Group $group
     * @param UpdateGroupAction $action
     * @return string
     */
    public function update_org(UpdateGroupRequest $request,$course_id, $group_id, UpdateGroupAction $action)
    {
        try {
            $group = Group::where('id','=',$group_id)->first();
//            $groups = Group::where('course_id','=',$course_id)->get();
//            $course = DB::table('courses')
//                ->where('id','=', $course_id)
//                ->first();

            $request->merge([
                'group'=>$group
            ]);
            $dto = UpdateGroupDTO::fromArray($request->all());
            $action->execute($dto);
        }catch (\Exception $exception)
        {
            return redirect()->back();
        }
        Alert::success('Success Title', 'Гуруҳ мувофаққиятли ўзгартирилди');
        return redirect()->route('course.itemGroup', $course_id);
//        return view('admin.groups.groups_show', compact('course','groups'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * @param Group $group
     * @return \Illuminate\Http\RedirectResponse
     */
    public function active(Group $group)
    {
        DB::table('groups')
            ->where('id','=', $group->id)
            ->update([
                'active'=>0
            ]);
        Alert::success('Success Title', 'Гуруҳ мувофаққиятли тугатилди');
        return redirect()->route('group.index');
    }

    /**
     * @param Group $group
     * @return string
     */
    public function active_org($course_id, $group_id)
    {
        DB::table('groups')
            ->where('id','=', $group_id)
            ->update([
                'active'=>0
            ]);
        $course = DB::table('courses')
            ->where('id','=', $course_id)
            ->orderBy('created_at','desc')
            ->first();
        $groups = Group::where('course_id','=',$course_id)
            ->orderBy('created_at','desc')
            ->get();
//        Alert::success('Success Title', 'Гуруҳ мувофаққиятли тугатилди');

        return view('admin.groups.groups_show', compact('course','groups'));
    }

    /**
     * @param Group $group
     * @return \Illuminate\Http\RedirectResponse
     */
    public function noactive(Group $group)
    {
        DB::table('groups')
            ->where('id','=', $group->id)
            ->update([
                'active'=>1
            ]);
        Alert::success('Success Title', 'Гуруҳ мувофаққиятли активлаштирилди');
        return redirect()->route('group.index');
    }

    public function noactive_org($course_id, $group_id)
    {
        DB::table('groups')
            ->where('id','=', $group_id)
            ->update([
                'active'=>1
            ]);
        $course = DB::table('courses')
            ->where('id','=', $course_id)
            ->orderBy('created_at','desc')
            ->first();
        $groups = Group::where('course_id','=',$course_id)
            ->orderBy('created_at','desc')
            ->get();
//        Alert::success('Success Title', 'Гуруҳ мувофаққиятли активлаштирилди');
        return view('admin.groups.groups_show', compact('course','groups'));
    }

    /**
     * @param Group $group
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|void
     */
    public function group_item(Group $group)
    {
        $students = Student::where('group_id','=',$group->id)
            ->orderBy('created_at','desc')
            ->get();
        return view('admin.students.students_show', compact('students', 'group'));
    }
}

resources/views/admin/groups/create.blade.php
@extends('admin.layouts.master')
@section('title', 'Гуруҳ яратиш')
@section('content')
    <div class="card">

        <div class="card-body">
            <form class="" action="{{route('group.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('POST')
                <div class="mb-3">
                    <label for="group_title">Гуруҳ номи</label>
                    <input value="{{old('group_title')}}" name="group_title" class="form-control @error('group_title') is-invalid @enderror"
                           type="text" placeholder="Гуруҳ номи">
                    @error('group_title')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <div class="col-form-label">Гуруҳ йўналишини танланг</div>
                    <select name="course_id" class="js-example-basic-single col-sm-12 @error('course_id') is-invalid @enderror">
                        <option disabled selected>гуруҳ йўналишини танланг</option>
                        @foreach($courses as $course)
                            <option value="{{$course->id}}">{{$course->course_title." (".$course->showStudyPlan->plan_title.")"}}</option>
                        @endforeach
                    </select>
                    @error('course_id')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>


                <div class="mb-3">
                    <label for="start_date">Гуруҳда ўқиш бошланиш вақти</label>
                    <input value="{{old('start_date')}}" name="start_date" class="form-control @error('start_date') is-invalid @enderror"
                           type="date" placeholder="Старт">
                    @error('start_date')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="end_date">Гуруҳда ўқиш тугаш вақти</label>
                    <input value="{{old('end_date')}}" name="end_date" class="form-control @error('end_date') is-invalid @enderror"
                           type="date" placeholder="Конец">
                    @error('end_date')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="teacher_one">Ўқув дарси раиси</label>
                    <input value="{{old('teacher_one')}}" name="teacher_one" class="form-control @error('teacher_one') is-invalid @enderror"
                           type="text" placeholder="Ўқув дарси раиси 1">
                    @error('teacher_one')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="teacher_two">Ўқув дарси раиси</label>
                    <input value="{{old('teacher_two')}}" name="teacher_two" class="form-control @error('teacher_two') is-invalid @enderror"
                           type="text" placeholder="Ўқув дарси раиси 2">
                    @error('teacher_two')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="organization">Гуруҳ қайси ташкилотни буюртмаси</label>
                    <input value="{{old('organization')}}" name="organization" class="form-control @error('organization') is-invalid @enderror"
                           type="text" placeholder="Ташкилот номи">
                    @error('organization')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Гуруҳ яратиш</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/groups/edit.blade.php
@extends('admin.layouts.master')
@section('title', $group->group_title.'-гуруҳ таҳрирлаш')
@section('content')
    <div class="card">

        <div class="card-body">
            <form class="" action="{{route('group.update', $group)}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')

                <div class="mb-3">
                    <label for="group_title">Гуруҳ номи</label>
                    <input value="{{$group->group_title}}" name="group_title" class="form-control @error('group_title') is-invalid @enderror"
                           type="text" placeholder="Гуруҳ номи">
                    @error('group_title')
                    <span class="invalid-feedback" role="alert">
                          <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <div class="col-form-label">Гуруҳ йўналишини танланг</div>
                    <select name="course_id" class="js-example-basic-single col-sm-12 @error('course_id') is-invalid @enderror">
                        <option disabled selected>Гуруҳ йўналишини танланг</option>
                        @foreach($courses as $course)
                            @if($course->id == $group->course_id)
                                <option selected value="{{$course->id}}">{{$course->course_title." (".$course->showStudyPlan->plan_title.")"}}</option>
                            @else
                                <option value="{{$course->id}}">{{$course->course_title." (".$course->showStudyPlan->plan_title.")"}}</option>
                            @endif
                        @endforeach
                    </select>
                    @error('course_id')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="start_date">Гуруҳда ўқиш бошланиш вақти2</label>
                    <input value="{{$start_date}}" name="start_date" class="form-control @error('start_date') is-invalid @enderror"
                           type="date">
                    @error('start_date')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="end_date">Гуруҳда ўқиш тугаш вақти</label>
                    <input value="{{$end_date}}" name="end_date" class="form-control @error('end_date') is-invalid @enderror"
                           type="date">
                    @error('end_date')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="teacher_one">Ўқув дарси раиси</label>
                    <input value="{{$group->teacher_one}}" name="teacher_one" class="form-control @error('teacher_one') is-invalid @enderror"
                           type="text" placeholder="Ўқув дарси раиси 1">
                    @error('teacher_one')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="teacher_two">Ўқув дарси раиси</label>
                    <input value="{{$group->teacher_two}}" name="teacher_two" class="form-control @error('teacher_two') is-invalid @enderror"
                           type="text" placeholder="Ўқув дарси раиси 2">
                    @error('teacher_two')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="organization">Гуруҳ қайси ташкилотни буюртмаси</label>
                    <input value="{{$group->organization}}" name="organization" class="form-control @error('organization') is-invalid @enderror"
                           type="text" placeholder="Ташкилот номи">
                    @error('organization')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Гуруҳни ўзгартириш</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/groups/index.blade.php
@extends('admin.layouts.master')
@section('title', 'Гуруҳлар')
@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>СТ Универсалда гуруҳлар жадвали</h5>
                        <span>Ушбу жадвалдан сиз таълим муассасидаги гуруҳларни кўришингиз, таҳрирлаш ишларини, шунингдек гуруҳни базадан ўчириб ташлашингиз мумкин.</span>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive product-table">
                            <table class="display" id="basic-1">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th class="col-sm-2">Гуруҳ номи</th>
                                    <th class="col-sm-3">Йўналиш номи</th>
                                    <th class="col-sm-2">Бошланиш</th>
                                    <th class="col-sm-2">Тугаш</th>
                                    <th class="col-sm-3">Раислар</th>
                                    <th class="col-sm-3">Ташкилот</th>
                                    <th class="col-sm-2">Ҳолат</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($groups as $group)
                                    <tr>
                                        <td>{{$loop->index+1}}</td>
                                        <td class="col-sm-1">
                                            <a target="_blank" href="{{route('group.itemStudent', $group)}}">{{$group->group_title}}</a>
                                        </td>
                                        <td class="col-sm-3">
                                            {{$group->kurslar->course_title." (".$group->kurslar->showStudyPlan->plan_title.") ".substr($group->end_date,6,9)}}
                                        </td>
                                        <td class="col-sm-2">
                                            {{$group->start_date}}
                                        </td>
                                        <td class="col-sm-2">
                                            {{$group->end_date}}
                                        </td>
                                        <td class="col-sm-1">
                                            {{$group->teacher_one." ".$group->teacher_two}}
                                        </td>
                                        <td class="col-sm-1">
                                            {{$group->organization}}
                                        </td>
                                        <td class="col-sm-1">
                                            @if($group->active == 1)
                                                <a href="{{route('group.active', $group)}}" class="btn btn-success" style="padding: 5px 10px"><i data-feather="check"></i></a>
                                            @elseif($group->active == 0)
                                                <a href="{{route('group.noactive', $group)}}" class="btn btn-danger" style="padding: 5px 10px"><i data-feather="x-circle"></i></a>
                                            @endif
                                        </td>
                                        <td class="col-sm-3">
                                            <a class="btn btn-primary" href="{{route('group.edit', $group)}}" style="padding: 10px 15px;"><i class="far fa-edit"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@push('script')
    <script type="text/javascript">

        $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Ushbu kursni o'chirmoqchimisiz?`,
                // text: "If you delete this, it will be gone forever.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });

    </script>
@endpush