routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm']);

Route::middleware(['middleware'=>'back'])->group(function (){
    Auth::routes([
//        'register'=>false
    ]);

});

Route::group(['prefix'=>'dashboard', 'middleware'=>['auth', 'admin', 'back']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'adminpanel'])->name('adminpanel');
    Route::resource('/direction', \App\Http\Controllers\Admin\YonalishController::class);
    Route::resource('/course', \App\Http\Controllers\Admin\CourseController::class);
    Route::resource('/group', \App\Http\Controllers\Admin\GroupController::class);
    Route::resource('/student', \App\Http\Controllers\Admin\StudentController::class);
    Route::get('/active/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'active'])->name('student.active');
    Route::get('/active/group/student/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'activeGroupStudent'])->name('activeGroupStudent');
    Route::get('/noactive/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'noactive'])->name('student.noactive');
    Route::get('/noactive/group/student/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'noactiveGroupStudent'])->name('noactiveGroupStudent');
    Route::get('/certificate/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'certi'])->name('student.certi');
    Route::get('/plastik/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'plastik'])->name('student.plastik');
    Route::get('/enable/{group}', [\App\Http\Controllers\Admin\GroupController::class, 'active'])->name('group.active');
    Route::get('/enable_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'active_org'])->name('group.active_org');
    Route::get('/disable_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'noactive_org'])->name('group.noactive_org');
    Route::get('/disable/{group}', [\App\Http\Controllers\Admin\GroupController::class, 'noactive'])->name('group.noactive');
    Route::get('/course/groups/{course}', [\App\Http\Controllers\Admin\CourseController::class, 'course_item'])->name('course.itemGroup');
    Route::get('/course/groups/create/{course}', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupCourse'])->name('createGroupCourse');
    Route::post('/course/groups/create/store', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupStore'])->name('createGroupCourseStore');
    Route::get('/course/groups/create/student/{group}', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupCourseStudent'])->name('createGroupCourseStudent');
    Route::post('/course/groups/student/store', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupCourseStudentStore'])->name('createGroupCourseStudentStore');

    Route::get('/group/students/{group}', [\App\Http\Controllers\Admin\GroupController::class, 'group_item'])->name('group.itemStudent');
    Route::get('/group/students/edit/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'editGroupStudent'])->name('editGroupStudent');
    Route::put('/group/students/edit/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'updateGroupStudent'])->name('updateGroupStudent');
    Route::resource('/guvohnoma', \App\Http\Controllers\Admin\GuvohnomaController::class);
    Route::get('/edit_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'edit_org'])->name('group.edit_org');
    Route::put('/group_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'update_org'])->name('group.update_org');
});

Route::get('/users/{student}',[\App\Http\Controllers\Admin\StudentController::class, 'show'])->name('show.info');

resources/views/admin/courses/create.blade.php
@extends('admin.layouts.master')
@section('title', 'Йўналиш яратиш')
@section('content')
    <div class="card">

        <div class="card-body">
            <form class="" action="{{route('course.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('POST')
                <div class="mb-3">
                    <label for="course_title">Йўналиш номи</label>
                    <input value="{{old('course_title')}}" name="course_title" class="form-control @error('course_title') is-invalid @enderror"
                           type="text" placeholder="Йўналиш номи">
                    @error('course_title')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <div class="col-form-label">Ўқув режани танланг</div>
                    <select name="stude_plan_id" class="js-example-basic-single col-sm-12 @error('stude_plan_id') is-invalid @enderror">
                        <option disabled selected>Ўқув режани танланг</option>
                            @foreach($study_plans as $study_plan)
                                <option value="{{$study_plan->id}}">{{$study_plan->plan_title}}</option>
                            @endforeach
                    </select>
                    @error('stude_plan_id')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="nazariy_soat">Назарий соат</label>
                    <input value="{{old('nazariy_soat')}}" name="nazariy_soat" class="form-control @error('nazariy_soat') is-invalid @enderror"
                           type="number" placeholder="Назарий соат">
                    @error('nazariy_soat')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="amaliy_soat">Амалий соат</label>
                    <input value="{{old('amaliy_soat')}}" name="amaliy_soat" class="form-control @error('amaliy_soat') is-invalid @enderror"
                           type="number" placeholder="Амалий соат">
                    @error('amaliy_soat')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Йўналиш яратиш</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/courses/createGroupCourse.blade.php
@extends('admin.layouts.master')
@section('title', 'Гуруҳ яратиш')
@section('content')
    <div class="card">

        <div class="card-body">
            <form class="" action="{{route('createGroupCourseStore')}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('POST')
                <div class="mb-3">
                    <label for="group_title">Гуруҳ номи</label>
                    <input value="{{old('group_title')}}" name="group_title" class="form-control @error('group_title') is-invalid @enderror"
                           type="text" placeholder="Гуруҳ номи">
                    @error('group_title')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <div class="col-form-label">Гуруҳ йўналишини танланг</div>
                    <select name="course_id" class="js-example-basic-single col-sm-12 @error('course_id') is-invalid @enderror">
{{--                        <option disabled selected>гуруҳ йўналишини танланг</option>--}}
                        <option selected value="{{$course->id}}">{{$course->course_title." (".$course->showStudyPlan->plan_title.")"}}</option>
                    </select>
                    @error('course_id')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>


                <div class="mb-3">
                    <label for="start_date">Гуруҳда ўқиш бошланиш вақти</label>
                    <input value="{{old('start_date')}}" name="start_date" class="form-control @error('start_date') is-invalid @enderror"
                           type="date" placeholder="Старт">
                    @error('start_date')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="end_date">Гуруҳда ўқиш тугаш вақти</label>
                    <input value="{{old('end_date')}}" name="end_date" class="form-control @error('end_date') is-invalid @enderror"
                           type="date" placeholder="Конец">
                    @error('end_date')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="teacher_one">Ўқув дарси раиси</label>
                    <input value="{{old('teacher_one')}}" name="teacher_one" class="form-control @error('teacher_one') is-invalid @enderror"
                           type="text" placeholder="Ўқув дарси раиси 1">
                    @error('teacher_one')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="teacher_two">Ўқув дарси раиси</label>
                    <input value="{{old('teacher_two')}}" name="teacher_two" class="form-control @error('teacher_two') is-invalid @enderror"
                           type="text" placeholder="Ўқув дарси раиси 2">
                    @error('teacher_two')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="organization">Гуруҳ қайси ташкилотни буюртмаси</label>
                    <input value="{{old('organization')}}" name="organization" class="form-control @error('organization') is-invalid @enderror"
                           type="text" placeholder="Ташкилот номи">
                    @error('organization')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <input type="hidden" name="course" class="d-none" value="{{ $course->id }}">
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Гуруҳ яратиш</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/courses/createGroupCourseStudent.blade.php
@extends('admin.layouts.master')
@section('title', 'Тингловчи яратиш')
@section('content')
    <div class="card">

        <div class="card-body">
            <form class="" action="{{route('createGroupCourseStudentStore')}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('POST')
                <div class="mb-3">
                    <label for="student_fio">Тингловчи Ф.И.О</label>
                    <input value="{{old('student_fio')}}" name="student_fio" class="form-control @error('student_fio') is-invalid @enderror"
                           type="text" placeholder="Тингловчи Ф.И.О">
                    @error('student_fio')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <div class="col-form-label">Гуруҳни танланг</div>
                    <select name="group_id" class="js-example-basic-single col-sm-12 @error('group_id') is-invalid @enderror">
                        <option selected value="{{$group->id}}">{{$group->group_title." ( ".$group->kurslar->course_title."(".$group->kurslar->showStudyPlan->plan_title.")) ". substr($group->start_date,6,10)}}</option>
                    </select>
                    @error('group_id')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="malaka">Курсни киритинг</label>
                    <input value="{{old('malaka')}}" name="malaka" class="form-control @error('malaka') is-invalid @enderror"
                           type="text" placeholder="Курсни киритинг">
                    @error('malaka')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <div class="col-form-label">Турни танланг</div>
                    <select name="guvohnoma_id" class="js-example-basic-single col-sm-12 @error('guvohnoma_id') is-invalid @enderror">
                        <option disabled selected>Турни танланг</option>
                        @foreach($guvohnomas as $guvohnoma)
                            <option value="{{$guvohnoma->id}}">{{$guvohnoma->tur_title}}</option>
                        @endforeach
                    </select>
                    @error('group_id')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="razryad">Разрядни киритинг</label>
                    <input value="{{old('razryad')}}" name="razryad" class="form-control @error('razryad') is-invalid @enderror"
                           type="text" placeholder="Разрядни киритинг">
                    @error('razryad')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>



                <div class="mb-3">
                    <label for="pasport_seria">Пасспорт серия</label>
                    <input maxlength="2" value="{{old('pasport_seria')}}" name="pasport_seria" class="form-control @error('pasport_seria') is-invalid @enderror"
                           type="text" placeholder="Пасспорт серия">
                    @error('pasport_seria')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="pasport_number">Пасспорт рақам</label>
                    <input value="{{old('pasport_number')}}" name="pasport_number" class="form-control @error('pasport_number') is-invalid @enderror"
                           type="number" placeholder="Пасспорт рақам">
                    @error('pasport_number')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="amaliy_baho">Тингловчи амалий баҳоси</label>
                    <input value="{{old('amaliy_baho')}}" name="amaliy_baho" class="form-control @error('amaliy_baho') is-invalid @enderror"
                           type="number" placeholder="Тингловчи амалий баҳоси">
                    @error('amaliy_baho')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="nazariy_baho">Тингловчи назарий баҳоси</label>
                    <input value="{{old('nazariy_baho')}}" name="nazariy_baho" class="form-control @error('nazariy_baho') is-invalid @enderror"
                           type="number" placeholder="Тингловчи назарий баҳоси">
                    @error('nazariy_baho')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="profession">Тингловчининг касби</label>
                    <input value="{{old('profession')}}" name="profession" class="form-control @error('profession') is-invalid @enderror"
                           type="text" placeholder="Тингловчининг касби">
                    @error('profession')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="student_img">Тингловчининг расми</label>
                    <input name="student_img" class="form-control image @error('student_img') is-invalid @enderror" type="file" id="imageUpload"><br>
                    <input type="hidden" name="x1" value="" />
                    <input type="hidden" name="y1" value="" />
                    <input type="hidden" name="w" value="" />
                    <input type="hidden" name="h" value="" />
                    <p><img id="previewimage" style="display:none;"/></p>
                    @if ($path = \Illuminate\Support\Facades\Session::get('path'))
                        <img width="100%" height="100%" src="{{ $path }}" />
                    @endif
                    @error('student_img')
                    <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Тингловчини яратиш</button>
                </div>
            </form>

        </div>
    </div>
@endsection
@push('style')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/imgareaselect/0.9.10/css/imgareaselect-default.css"/>
@endpush
@push('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/imgareaselect/0.9.10/js/jquery.imgareaselect.min.js"></script>
    <script>
        jQuery(function($) {
            var p = $("#previewimage");

            $("body").on("change", ".image", function(){
                var imageReader = new FileReader();
                imageReader.readAsDataURL(document.querySelector(".image").files[0]);

                imageReader.onload = function (oFREvent) {
                    p.attr('src', oFREvent.target.result).fadeIn();
                };
            });

            $('#previewimage').imgAreaSelect({
                onSelectEnd: function (img, selection) {
                    $('input[name="x1"]').val(selection.x1);
                    $('input[name="y1"]').val(selection.y1);
                    $('input[name="w"]').val(selection.width);
                    $('input[name="h"]').val(selection.height);
                }
            });
        });
    </script>
@endpush

resources/views/admin/courses/edit.blade.php
@extends('admin.layouts.master')
@section('title', 'Йўналишни таҳрирлаш')
@section('content')
    <div class="card">

        <div class="card-body">
            <form class="" action="{{route('course.update', $course)}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="mb-3">
                    <label for="course_title">Йўналиш номи</label>
                    <input value="{{$course->course_title}}" name="course_title" class="form-control @error('course_title') is-invalid @enderror"
                           type="text">
                    @error('course_title')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <div class="col-form-label">Ўқув режани танланг</div>
                    <select name="stude_plan_id" class="js-example-basic-single col-sm-12 @error('stude_plan_id') is-invalid @enderror">
                        @foreach($plans as $plan)
                            @if($plan->id == $course->stude_plan_id)
                                <option selected value="{{$plan->id}}">{{$plan->plan_title}}</option>
                            @else
                                <option value="{{$plan->id}}">{{$plan->plan_title}}</option>
                            @endif
                        @endforeach
                    </select>
                    @error('stude_plan_id')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="nazariy_soat">Назарий соат</label>
                    <input value="{{$course->nazariy_soat}}" name="nazariy_soat" class="form-control @error('nazariy_soat') is-invalid @enderror"
                           type="number" placeholder="Назарий соат">
                    @error('nazariy_soat')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="amaliy_soat">Амалий соат</label>
                    <input value="{{$course->amaliy_soat}}" name="amaliy_soat" class="form-control @error('amaliy_soat') is-invalid @enderror"
                           type="number" placeholder="Амалий соат">
                    @error('amaliy_soat')
                    <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                    @enderror
                </div>

                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Йўналишни таҳрирлаш</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/courses/index.blade.php
@extends('admin.layouts.master')
@section('title', 'Йўналишлар жадвали')
@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>СТ Универсалда йўналишлар жадвали</h5>
                        <span>Ушбу жадвалдан сиз таълим муассасидаги йўналишларни кўришингиз, таҳрирлаш ишларини, шунингдек йўналишни базадан ўчириб ташлашингиз мумкин.</span>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive product-table">
                            <table class="display" id="basic-1">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th class="col-sm-3">йўналиш номи</th>
                                    <th class="col-sm-3">Ўқув режаси</th>
                                    <th class="col-sm-3">Назарий соат</th>
                                    <th class="col-sm-3">Амалий соат</th>
                                    <th>Таҳрирлаш</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($courses as $course)
                                    <tr>
                                        <td>{{$loop->index+1}}</td>
                                        <td class="col-sm-4">
                                            <a target="_blank" href="{{route('course.itemGroup', $course)}}">{{$course->course_title}}</a>
                                        </td>
                                        <td class="col-sm-2">
                                            {{$course->showStudyPlan->plan_title}}
                                        </td>
                                        <td class="col-sm-1">
                                            {{$course->nazariy_soat}}
                                        </td>
                                        <td class="col-sm-1">
                                            {{$course->amaliy_soat}}
                                        </td>
                                        <td class="col-sm-3">
                                            <a class="btn btn-primary" href="{{route('course.edit', $course)}}" style="padding: 6px 10px ;"><i class="far fa-edit"></i></a>
{{--                                            <form class="d-inline-block" method="post" action="{{route('course.destroy', $course)}}">--}}
{{--                                                @csrf--}}
{{--                                                @method('DELETE')--}}
{{--                                                <button type="submit" class="btn btn-danger show_confirm" data-toggle="tooltip" title='Delete' style="padding: 6px 10px ;"><i class="far fa-trash-alt"></i></button>--}}
{{--                                            </form>--}}

                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@push('script')
    <script type="text/javascript">

        $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Ушбу йўналишни ўчирмоқчимисиз?`,
                // text: "If you delete this, it will be gone forever.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });

    </script>
@endpush