routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm']);

Route::middleware(['middleware'=>'back'])->group(function (){
    Auth::routes([
//        'register'=>false
    ]);

});

Route::group(['prefix'=>'dashboard', 'middleware'=>['auth', 'admin', 'back']], function (){
    Route::get('/', [\App\Http\Controllers\HomeController::class, 'adminpanel'])->name('adminpanel');
    Route::resource('/direction', \App\Http\Controllers\Admin\YonalishController::class);
    Route::resource('/course', \App\Http\Controllers\Admin\CourseController::class);
    Route::resource('/group', \App\Http\Controllers\Admin\GroupController::class);
    Route::resource('/student', \App\Http\Controllers\Admin\StudentController::class);
    Route::get('/active/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'active'])->name('student.active');
    Route::get('/active/group/student/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'activeGroupStudent'])->name('activeGroupStudent');
    Route::get('/noactive/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'noactive'])->name('student.noactive');
    Route::get('/noactive/group/student/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'noactiveGroupStudent'])->name('noactiveGroupStudent');
    Route::get('/certificate/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'certi'])->name('student.certi');
    Route::get('/plastik/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'plastik'])->name('student.plastik');
    Route::get('/enable/{group}', [\App\Http\Controllers\Admin\GroupController::class, 'active'])->name('group.active');
    Route::get('/enable_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'active_org'])->name('group.active_org');
    Route::get('/disable_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'noactive_org'])->name('group.noactive_org');
    Route::get('/disable/{group}', [\App\Http\Controllers\Admin\GroupController::class, 'noactive'])->name('group.noactive');
    Route::get('/course/groups/{course}', [\App\Http\Controllers\Admin\CourseController::class, 'course_item'])->name('course.itemGroup');
    Route::get('/course/groups/create/{course}', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupCourse'])->name('createGroupCourse');
    Route::post('/course/groups/create/store', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupStore'])->name('createGroupCourseStore');
    Route::get('/course/groups/create/student/{group}', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupCourseStudent'])->name('createGroupCourseStudent');
    Route::post('/course/groups/student/store', [\App\Http\Controllers\Admin\CourseController::class, 'createGroupCourseStudentStore'])->name('createGroupCourseStudentStore');

    Route::get('/group/students/{group}', [\App\Http\Controllers\Admin\GroupController::class, 'group_item'])->name('group.itemStudent');
    Route::get('/group/students/edit/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'editGroupStudent'])->name('editGroupStudent');
    Route::put('/group/students/edit/{student}', [\App\Http\Controllers\Admin\StudentController::class, 'updateGroupStudent'])->name('updateGroupStudent');
    Route::resource('/guvohnoma', \App\Http\Controllers\Admin\GuvohnomaController::class);
    Route::get('/edit_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'edit_org'])->name('group.edit_org');
    Route::put('/group_org/{course_id}/{group_id}', [\App\Http\Controllers\Admin\GroupController::class, 'update_org'])->name('group.update_org');
});

Route::get('/users/{student}',[\App\Http\Controllers\Admin\StudentController::class, 'show'])->name('show.info');

resources/views/admin/partials/navbar.blade.php
<div class="page-header">
    <div class="header-wrapper row m-0">
        <form class="form-inline search-full col" action="#" method="get">
            <div class="form-group w-100">
                <div class="Typeahead Typeahead--twitterUsers">
                    <div class="u-posRelative">
                        <input class="demo-input Typeahead-input form-control-plaintext w-100" type="text" placeholder="Search Cuba .." name="q" title="" autofocus>
                        <div class="spinner-border Typeahead-spinner" role="status"><span class="sr-only">Loading...</span></div><i class="close-search" data-feather="x"></i>
                    </div>
                    <div class="Typeahead-menu"></div>
                </div>
            </div>
        </form>
        <div class="header-logo-wrapper col-auto p-0">
            <div class="logo-wrapper"><a href="index.html"><img class="img-fluid" src="https://style.softgo.uz/assets/images/logo/logo.png" alt=""></a></div>
            <div class="toggle-sidebar"><i class="status_toggle middle sidebar-toggle" data-feather="align-center"></i></div>
        </div>
        <div class="left-header col horizontal-wrapper ps-0">
            <ul class="horizontal-menu">


            </ul>
        </div>
        <div class="nav-right col-8 pull-right right-header p-0">
            <ul class="nav-menus">
                <li class="language-nav">
                    <div class="translate_wrapper">
                        <div class="current_lang">
                            <div class="lang"><i class="flag-icon flag-icon-uz"></i><span class="lang-txt">UZ                               </span></div>
                        </div>
                        <div class="more_lang">
                            <div class="lang selected" data-value="en"><i class="flag-icon flag-icon-uz"></i><span class="lang-txt">Uzbek<span> (UZ)</span></span></div>
                            <div class="lang" data-value="de"><i class="flag-icon flag-icon-ru"></i><span class="lang-txt">Russia</span></div>
                            <div class="lang" data-value="es"><i class="flag-icon flag-icon-us"></i><span class="lang-txt">English</span></div>
                        </div>
                    </div>
                </li>
                <li><span class="header-search"><i data-feather="search"></i></span></li>
                <li>
                    <div class="mode"><i class="fa fa-moon-o"></i></div>
                </li>

                <li class="maximize"><a class="text-dark" href="#!" onclick="javascript:toggleFullScreen()"><i data-feather="maximize"></i></a></li>
                <li class="profile-nav onhover-dropdown p-0 me-0">
                    <div class="media profile-media"><img class="b-r-10" src="https://style.softgo.uz/assets/images/dashboard/profile.jpg" alt="">
                        <div class="media-body"><span>{{\Illuminate\Support\Facades\Auth::user()->lname." ".\Illuminate\Support\Facades\Auth::user()->name}}</span>
                            <p class="mb-0 font-roboto">Admin <i class="middle fa fa-angle-down"></i></p>
                        </div>
                    </div>
                    <ul class="profile-dropdown onhover-show-div">
                        <li><a href="#"><i data-feather="settings"></i><span>Созламалар</span></a></li>
                        <li>
                            <a href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                <i data-feather="log-in"> </i><span>
                                {{ __('Чиқиш') }}
                                </span>
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <script class="result-template" type="text/x-handlebars-template">
            <div class="ProfileCard u-cf">
            <div class="ProfileCard-avatar"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-airplay m-0"><path d="M5 17H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-1"></path><polygon points="12 15 17 21 7 21 12 15"></polygon></svg></div>
            <div class="ProfileCard-details">
            <div class="ProfileCard-realName"></div>
            </div>
            </div>
          </script>
        <script class="empty-template" type="text/x-handlebars-template"><div class="EmptyMessage">Your search turned up 0 results. This most likely means the backend is down, yikes!</div></script>
    </div>
</div>

resources/views/admin/partials/sidebar.blade.php
<div class="sidebar-wrapper">
    <div>
        <div class="logo-wrapper"><a href="">
                    <span style="font-size: 20px" class="text-bg-info">СТ<span class="text-warning">Универсал</span></span>
                         <div class="back-btn"><i class="fa fa-angle-left"></i>
                         </div>
            <div class="toggle-sidebar"><i class="status_toggle middle sidebar-toggle" data-feather="grid"> </i></div>
            </a></div>
        <div class="logo-icon-wrapper"><a href="index.html"><img class="img-fluid" src="https://style.softgo.uz/assets/images/logo/logo-icon.png" alt=""></a></div>
        <nav class="sidebar-main">
            <div class="left-arrow" id="left-arrow"><i data-feather="arrow-left"></i></div>
            <div id="sidebar-menu">
                <ul class="sidebar-links" id="simple-bar">
                    <li class="back-btn"><a href="index.html"><img class="img-fluid" src="https://style.softgo.uz/assets/images/logo/logo-icon.png" alt=""></a>
                        <div class="mobile-back text-end"><span>Back</span><i class="fa fa-angle-right ps-2" aria-hidden="true"></i></div>
                    </li>
                    <li class="sidebar-main-title">
                        <div>
                            <h6 class="">СТ Универсал</h6>
                            <p class="">Тизим бўлимлари</p>
                        </div>
                    </li>
                    <li class="sidebar-list ">
                        <a class="sidebar-link sidebar-title active" href="#">
                            <i data-feather="file-text"></i>
                            <span class="">Ўқув режа</span>
                        </a>
                        <ul class="sidebar-submenu {{(request()->is("dashboard/direction/create") || request()->is("dashboard/direction") || request()->is("dashboard/direction/*/edit")) ? "d-block" : ""}}">
                            <li><a target="_blank" class="" style="color: {{request()->is("dashboard/direction/create") ? "#7366ff" : ""}}" href="{{route("direction.create")}}">Ўқув режа яратиш</a></li>
                            <li><a target="_blank" class="" style="color: {{(request()->is("dashboard/direction") || request()->is("dashboard/direction/*/edit")) ? "#7366ff" : ""}}" href="{{route("direction.index")}}">Ўқув режалар</a></li>
                        </ul>
                    </li>
                    <li class="sidebar-list">
                        <a class="sidebar-link sidebar-title {{ request()->is("/dashboard/course/create") ? "active" : "" }}" href="#"><i data-feather="briefcase"></i><span class="">Йўналишлар</span></a>
                        <ul class="sidebar-submenu {{(request()->is('dashboard/course/create') || request()->is('dashboard/course') || request()->is('dashboard/course/*/edit') || request()->is('dashboard/course/groups/*')  || request()->is('dashboard/group/students/*')) ? 'd-block' : ''}}">
                            <li><a target="_blank" class="" style="color: {{request()->is('dashboard/course/create') ? '#7366ff' : ''}}" href="{{route('course.create')}}">Йўналишлар яратиш</a></li>
                            <li><a target="_blank" class="" style="color: {{(request()->is('dashboard/course') || request()->is('dashboard/course/*/edit') || request()->is('dashboard/course/groups/*') || request()->is('dashboard/group/students/*')) ? '#7366ff' : ''}}" href="{{route('course.index')}}">Йўналишлар рўйхати</a></li>
                        </ul>
                    </li>
                    <li class="sidebar-list">
                        <a class="sidebar-link sidebar-title" href="#"><i data-feather="users"></i><span class="">Гуруҳлар</span></a>
                        <ul class="sidebar-submenu {{(request()->is('dashboard/group/create') || request()->is('dashboard/group') || request()->is('dashboard/group/*/edit')) ? 'd-block' : ''}}">
                            <li><a target="_blank" class="" style="color: {{request()->is('dashboard/group/create') ? '#7366ff' : ''}}" href="{{route('group.create')}}">Гуруҳ яратиш</a></li>
                            <li><a target="_blank" class="" style="color: {{(request()->is('dashboard/group') || request()->is('dashboard/group/*/edit')) ? '#7366ff' : ''}}" href="{{route('group.index')}}">Гуруҳлар рўйхати</a></li>
                        </ul>
                    </li>
                    <li class="sidebar-list">
                        <a class="sidebar-link sidebar-title" href="#"><i data-feather="user"></i><span class="">Тингловчилар</span></a>
                        <ul class="sidebar-submenu {{(request()->is('dashboard/student/create') || request()->is('dashboard/student') || request()->is('dashboard/student/*/edit')) ? 'd-block' : ''}}">
                            <li><a target="_blank" class="" style="color: {{request()->is('dashboard/student/create') ? '#7366ff' : ''}}" href="{{route('student.create')}}">Тингловчи яратиш</a></li>
                            <li><a target="_blank" class="" style="color: {{(request()->is('dashboard/student') || request()->is('dashboard/student/*/edit')) ? '#7366ff' : ''}}" href="{{route('student.index')}}">Тингловчилар руйхати</a></li>
                        </ul>
                    </li>
{{--                    <li class="sidebar-list">--}}
{{--                        <a class="sidebar-link sidebar-title" href="#"><i data-feather="sidebar"></i><span class="">Гувохномалар</span></a>--}}
{{--                        <ul class="sidebar-submenu {{(request()->is('dashboard/guvohnoma/create') || request()->is('dashboard/guvohnoma') || request()->is('dashboard/guvohnoma/*/edit')) ? 'd-block' : ''}}">--}}
{{--                            <li><a class="" style="color: {{request()->is('dashboard/guvohnoma/create') ? '#7366ff' : ''}}" href="{{route('guvohnoma.create')}}">Гувохнома яратиш</a></li>--}}
{{--                            <li><a class="" style="color: {{(request()->is('dashboard/guvohnoma') || request()->is('dashboard/guvohnoma/*/edit')) ? '#7366ff' : ''}}" href="{{route('guvohnoma.index')}}">Гувохномалар рўйхати</a></li>--}}
{{--                        </ul>--}}
{{--                    </li>--}}
               </ul>
            </div>
            <div class="right-arrow" id="right-arrow"><i data-feather="arrow-right"></i></div>
        </nav>
    </div>
</div>